version: '3'
services:
  blog:
    container_name: blog
    build: ./src
    restart: always  
    ports:
      - "3000:3000" 
    working_dir: "/app"
    volumes:
    - ./src:/app
    - /app/node_modules/
    depends_on:
        - mongodb     
    networks:
      - blog_network
  mongodb:
    image: mongo:4.1.10
    container_name: "mongodb"
    restart: always
    volumes:
      - ./data/db:/data/db
    ports:
        - "27017:27017"        
    networks:
      - blog_network

networks:
  blog_network:
    driver: bridge